name: Build OTP Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container:
      image: alpine:3.22

    strategy:
      matrix:
        otp_version:
          - "28.1"
          - "28.0.4"
          - "27.3.4.3"
          - "27.2.4"
          - "27.1.3"
          - "27.0.1"
          - "26.2.5.15"
          - "26.1.2"
          - "26.0.2"
        rebar3_version:
          - "3.25.0"
        arch:
          - "x64"
          - "arm64"

    steps:
      - name: Checkout repository
        uses: taiki-e/checkout-action@v1
        with:
          persist-credentials: true

      - name: Build
        run: |
          chmod +x ./build.sh
          export OTP_VERSION=${{ matrix.otp_version }}
          export REBAR3_VERSION=${{ matrix.rebar3_version }}
          ./build.sh

      - name: Create tar.gz archive
        run: |
          cd /usr/local/lib/
          tar -czf /tmp/erlang-${{ matrix.otp_version }}-${{ matrix.arch }}.tar.gz erlang

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          apk add --no-cache github-cli
          gh release create otp-${{ matrix.otp_version }} \
            /tmp/erlang-${{ matrix.otp_version }}-${{ matrix.arch }}.tar.gz \
            --title "OTP ${{ matrix.otp_version }}" \
            --notes "OTP ${{ matrix.otp_version }} built for Linux ${{ matrix.arch }}" \
            --repo ${{ github.repository }} || \
          gh release upload otp-${{ matrix.otp_version }} \
            /tmp/erlang-${{ matrix.otp_version }}-${{ matrix.arch }}.tar.gz \
            --repo ${{ github.repository }} \
            --clobber
