name: Build OTP Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container:
      image: alpine:3.22

    strategy:
      matrix:
        otp_version:
          - "28.1"
        rebar3_version:
          - "3.25.0"
        arch:
          - "x64"
          - "arm64"

    steps:
      - name: Checkout repository
        uses: taiki-e/checkout-action@v1
        with:
          persist-credentials: true

      - name: Build
        run: |
          chmod +x ./build.sh
          export OTP_VERSION=${{ matrix.otp_version }}
          export REBAR3_VERSION=${{ matrix.rebar3_version }}
          ./build.sh

      - name: Create tar.gz archive
        run: |
          cd /usr/local/lib/
          tar -czf /tmp/erlang-${{ matrix.otp_version }}-${{ matrix.arch }}.tar.gz erlang

      - name: Install Release Dependencies
        run: |
          apk --no-cache add curl ca-certificates

      - name: Upload to release
        uses: ahsand97/upload-assets-to-release-with-go@v0.1.1
        with:
          tag: otp-${{ matrix.otp_version }}
          files: /tmp/erlang-${{ matrix.otp_version }}-${{ matrix.arch }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
